# Generated by Django 5.2.8 on 2025-12-03 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('especialidad', models.CharField(choices=[('co2', 'CO2'), ('nh3', 'NH3'), ('freon', 'Freon'), ('glicol', 'Glicol')], max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('consecutivo', models.CharField(max_length=50, unique=True)),
                ('validez_oferta', models.DateField()),
                ('tipo_proyecto', models.CharField(choices=[('pliego', 'Proyecto de Pliego'), ('cotizacion', 'Cotización')], max_length=20)),
                ('formas_pago', models.TextField()),
                ('cliente', models.CharField(max_length=200)),
                ('ubicacion_geografica', models.CharField(max_length=300)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('version_presupuesto', models.CharField(default='1.0', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_creados', to=settings.AUTH_USER_MODEL)),
                ('ingeniero_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
