# Generated by Django 5.2.8 on 2025-12-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='especialidades',
            field=models.ManyToManyField(help_text='Seleccione las especialidades relacionadas con este presupuesto.', related_name='presupuestos_relacionados', to='presupuestos.especialidad'),
        ),
    ]
