# Generated by Django 5.2.8 on 2026-01-11 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0002_especialidad_remove_presupuesto_especialidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('lectura', 'Solo lectura'), ('escritura', 'Lectura y escritura')], default='lectura', max_length=10)),
                ('fecha_concesion', models.DateTimeField(auto_now_add=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_compartidos', to='presupuestos.presupuesto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_compartidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'permisos de presupuestos',
                'unique_together': {('presupuesto', 'usuario')},
            },
        ),
    ]
