# Generated by Django 5.2.8 on 2026-01-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_permisopresupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
