# Generated by Django 5.2.8 on 2026-02-16 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_presupuesto_consecutivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='dueno_original',
            field=models.ForeignKey(blank=True, help_text='Dueño original del presupuesto si es un préstamo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_prestados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='es_prestamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuesto_padre',
            field=models.ForeignKey(blank=True, help_text='Presupuesto original del cual se derivó este préstamo o versión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_derivadas', to='presupuestos.presupuesto'),
        ),
    ]
