# Generated by Django 5.2.8 on 2025-12-27 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0002_especialidad_remove_presupuesto_especialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuarto', models.CharField(help_text='Nombre del cuarto frío', max_length=100)),
                ('temperatura_requerida', models.DecimalField(decimal_places=2, help_text='Temperatura objetivo en °C', max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, help_text='Ancho en metros', max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, help_text='Largo en metros', max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, help_text='Alto en metros', max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=2, editable=False, help_text='Volumen en metros cúbicos', max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_rooms', to='presupuestos.presupuesto')),
            ],
            options={
                'verbose_name': 'cuarto frio',
                'verbose_name_plural': 'cuartos frios',
            },
        ),
    ]
