# Generated by Django 5.2.8 on 2026-01-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldrooms', '0001_initial'),
        ('presupuestos', '0002_especialidad_remove_presupuesto_especialidad_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coldroom',
            constraint=models.UniqueConstraint(fields=('presupuesto', 'nombre_cuarto'), name='unique_coldroom_per_presupuesto'),
        ),
    ]
