# Generated by Django 5.2.8 on 2026-01-06 04:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coldrooms', '0002_coldroom_unique_coldroom_per_presupuesto'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BombaGlicol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_bomba', models.CharField(choices=[('centrifuga', 'Centrífuga'), ('piston', 'Pistón'), ('diafragma', 'Diafragma'), ('tornillo', 'Tornillo')], max_length=20, verbose_name='Tipo de Bomba')),
                ('caudal_nominal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal Nominal (L/min)')),
                ('presion_trabajo', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión de Trabajo (bar)')),
                ('altura_elevacion', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Altura de Elevación (m)')),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Máxima (°C)')),
                ('material_carcasa', models.CharField(default='Acero Inoxidable', max_length=50, verbose_name='Material de Carcasa')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Bomba de Glicol',
                'verbose_name_plural': 'Bombas de Glicol',
            },
        ),
        migrations.CreateModel(
            name='Compresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_compresor', models.CharField(choices=[('tornillo', 'Tornillo'), ('alternativo', 'Alternativo'), ('scroll', 'Scroll'), ('centrifugo', 'Centrífugo')], max_length=20, verbose_name='Tipo de Compresor')),
                ('capacidad_refrigeracion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Refrigeración (TR)')),
                ('caudal_refrigerante', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal de Refrigerante (kg/h)')),
                ('presion_alta', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión Alta (bar)')),
                ('presion_baja', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión Baja (bar)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Compresor',
                'verbose_name_plural': 'Compresores',
            },
        ),
        migrations.CreateModel(
            name='Condensador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_condensador', models.CharField(choices=[('aire', 'Por Aire'), ('evaporativo', 'Evaporativo'), ('adiabatico', 'Adiabatico')], max_length=20, verbose_name='Tipo de Condensador')),
                ('capacidad_rechazo_calor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Rechazo de Calor (kW)')),
                ('temperatura_condensacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura de Condensación (°C)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Condensador',
                'verbose_name_plural': 'Condensadores',
            },
        ),
        migrations.CreateModel(
            name='Deshumificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capacidad_extraccion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Extracción (L/día)')),
                ('caudal_aire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal de Aire (m³/h)')),
                ('temperatura_operacion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura de Operación (°C)')),
                ('humedad_relativa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Humedad Relativa (%)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Deshumificador',
                'verbose_name_plural': 'Deshumificadores',
            },
        ),
        migrations.CreateModel(
            name='EnfriadorGlicol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capacidad_refrigeracion', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Capacidad de Refrigeración (kW)')),
                ('caudal_glicol', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal de Glicol (L/min)')),
                ('temperatura_entrada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Entrada (°C)')),
                ('temperatura_salida', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura Salida (°C)')),
                ('concentracion_glicol', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Concentración de Glicol (%)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Enfriador de Glicol',
                'verbose_name_plural': 'Enfriadores de Glicol',
            },
        ),
        migrations.CreateModel(
            name='Evaporador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ancho (mm)')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Alto (mm)')),
                ('profundidad', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Profundidad (mm)')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('tipo_evaporador', models.CharField(choices=[('aire_forzado', 'Aire Forzado'), ('estatica', 'Estática'), ('cascada', 'Cascada'), ('inundado', 'Inundado')], max_length=20, verbose_name='Tipo de Evaporador')),
                ('caudal_aire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal de Aire (m³/h)')),
                ('flecha_aire', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Flecha de Aire (m)')),
                ('temperatura_evaporacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura de Evaporación (°C)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Evaporador',
                'verbose_name_plural': 'Evaporadores',
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Motor ventilador 1, Resistencia de descongelación', max_length=50)),
                ('tension', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tensión (V)')),
                ('consumo_amperios', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Consumo (A)')),
                ('potencia_watts', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Potencia (W)')),
                ('object_id', models.PositiveBigIntegerField()),
                ('fases', models.CharField(choices=[('monofasico', 'Monofásico (1φ)'), ('bifasico', 'Bifásico (2φ)'), ('trifasico', 'Trifásico (3φ)')], default='trifasico', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
            },
        ),
        migrations.CreateModel(
            name='Resistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Motor ventilador 1, Resistencia de descongelación', max_length=50)),
                ('tension', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Tensión (V)')),
                ('consumo_amperios', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Consumo (A)')),
                ('potencia_watts', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Potencia (W)')),
                ('object_id', models.PositiveBigIntegerField()),
                ('tipo', models.CharField(choices=[('panel', 'Resistencia de Panel'), ('bandeja', 'Resistencia de Bandeja'), ('deshumificacion', 'Resistencia de Deshumificación'), ('calefaccion', 'Resistencia de Calefacción')], max_length=20, verbose_name='Tipo de Resistencia')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Resistencia',
                'verbose_name_plural': 'Resistencias',
            },
        ),
        migrations.CreateModel(
            name='Ventilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_equipo', models.CharField(choices=[('evaporador', 'Evaporador'), ('compresor', 'Compresor'), ('condensador', 'Condensador'), ('enfriador_glicol', 'Enfriador de Glicol'), ('deshumificador', 'Deshumificador'), ('ventilador', 'Ventilador'), ('bomba_glicol', 'Bomba de Glicol')], max_length=30, verbose_name='Tipo de Equipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_ventilador', models.CharField(choices=[('axial', 'Axial'), ('centrifugo', 'Centrífugo'), ('helicoidal', 'Helicoidal')], max_length=20, verbose_name='Tipo de Ventilador')),
                ('caudal_aire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Caudal de Aire (m³/h)')),
                ('presion_estatica', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión Estática (Pa)')),
                ('diametro_aspas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Diámetro de Aspas (mm)')),
                ('velocidad_rotacion', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Velocidad de Rotación (RPM)')),
                ('cold_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='coldrooms.coldroom', verbose_name='Cuarto Frío')),
            ],
            options={
                'verbose_name': 'Ventilador',
                'verbose_name_plural': 'Ventiladores',
            },
        ),
    ]
