# Generated by Django 5.2.8 on 2026-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaporador',
            name='caudal_aire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Caudal de Aire (m³/h)'),
        ),
        migrations.AlterField(
            model_name='evaporador',
            name='flecha_aire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Flecha de Aire (m)'),
        ),
    ]
